# Generated by Django 4.0.2 on 2022-04-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(default='', max_length=20, verbose_name='Фамилия клиента')),
                ('firstname', models.CharField(default='', max_length=20, verbose_name='Имя клиента')),
                ('middlename', models.CharField(blank=True, default='', max_length=20, verbose_name='Отчество клиента')),
                ('tag', models.TextField(blank=True, max_length=100, verbose_name='Примечание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления клиента')),
                ('number', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Номер телефона 7XXXXXXXXXX')),
                ('operator', models.DecimalField(decimal_places=0, max_digits=30, verbose_name='Код мобильного оператора')),
                ('timezone', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Часовой пояс клиента')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='', max_length=20, verbose_name='Тема сообщения')),
                ('tag', models.TextField(blank=True, max_length=100, verbose_name='Примечание')),
                ('date', models.DateTimeField(verbose_name='Время отправления сообщения')),
                ('status', models.BinaryField(max_length=10, verbose_name='Статус отправки')),
                ('mailing_list_id', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='id рассылки')),
                ('client_id', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='id клиента-получателя')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
