# Generated by Django 4.0.2 on 2022-04-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Содержание рассылки')),
                ('timestart', models.DateTimeField(auto_now_add=True, verbose_name='Время начала рассылки')),
                ('timefinish', models.DateTimeField(auto_now_add=True, verbose_name='Время окончания рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиены'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='message',
            name='theme',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Имя (необязательно)'),
        ),
        migrations.AddField(
            model_name='message',
            name='date2',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания сообщения2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='operator',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Код мобильного оператора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=models.DecimalField(decimal_places=0, default='+3', max_digits=3, verbose_name='Часовой пояс клиента'),
        ),
        migrations.AlterField(
            model_name='message',
            name='client_id',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='id клиента'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.TextField(max_length=10, verbose_name='Статус отправки'),
        ),
    ]
