# Generated by Django 4.0.2 on 2022-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_client_options_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.CharField(blank=True, max_length=30, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=models.DecimalField(decimal_places=0, default='', max_digits=3, verbose_name='Часовой пояс клиента'),
        ),
    ]
