# Generated by Django 4.0.2 on 2022-04-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_client_tag_alter_client_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='foperator',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Код мобильного оператора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='ftag',
            field=models.CharField(blank=True, max_length=30, verbose_name='Тег'),
        ),
    ]
