# Generated by Django 4.0.2 on 2022-04-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_alter_client_number_alter_mailing_msg_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='ftag',
            field=models.CharField(blank=True, max_length=30, verbose_name='Тег клиента'),
        ),
    ]
