# Generated by Django 4.0.2 on 2022-04-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_alter_mailing_ftag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(max_length=10, verbose_name='Статус отправки'),
        ),
    ]
